"""Added is_active_flag column

Revision ID: 94a7cfdf056c
Revises: 
Create Date: 2025-01-31 22:04:16.005867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a7cfdf056c'
down_revision = None
branch_labels = None
depends_on = None


# In your migration file (e.g., 94a7cfdf056c_added_is_active_flag_column.py)

def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_flag', sa.Boolean(), nullable=False, server_default='1'))  # default value '1' (active)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active_flag')

    # ### end Alembic commands ###
