"""Removed website column from Password model

Revision ID: e9e1e1b6a41d
Revises: 94a7cfdf056c
Create Date: 2025-02-01 08:26:18.956103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e1e1b6a41d'
down_revision = '94a7cfdf056c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
